service: importer

frameworkVersion: ">=1.9.0 <2.0.0"

plugins:
  - serverless-python-requirements

custom:
  stage: ${opt:stage, self:provider.stage}
  sshKey: ${env:aws_key}
  awsRegion: ${env:aws_region}
  awsImageId: ${env:aws_image_id}
  awsInstanceType: ${env:aws_instance_type}
  awsSecurityGroups: ${env:aws_security_groups}
  awsRdsSecurityGroup: ${env:aws_rds_security_group}
  subnet1: ${env:aws_subnet_1}
  subnet2: ${env:aws_subnet_2}
  pythonRequirements:
    dockerizePip: false

provider:
  name: aws
  region: ${self:custom.awsRegion}
  runtime: python3.6
  environment:
    aws_key: ${self:custom.sshKey}
    aws_region: ${self:custom.awsRegion}
    aws_image_id: ${self:custom.awsImageId}
    aws_instance_type: ${self:custom.awsInstanceType}
    aws_security_groups: ${self:custom.awsSecurityGroups}
    # aws_subnet_1: ${self:custom.subnet1}
    # aws_subnet_2: ${self:custom.subnet2}
    s3_bucket: {Ref: ScriptBucket}
    db_host: {"Fn::GetAtt": ["RDS","Endpoint.Address"]}
    db_port: {"Fn::GetAtt": ["RDS","Endpoint.Port"]}
    db_user: ${env:db_user}
    db_password: ${env:db_password}
    db_schema: ${env:db_schema}

  vpc:
    securityGroupIds:
      - "sg-b6039cfd"
    subnetIds:
      - "subnet-7ba13b51"
      - "subnet-f4cb9e82"
  # vpc:
  #   securityGroupIds:
  #     # - "sg-b6039cfd"
  #     - ${env:aws_security_groups}
  #     #- ${self:custom.awsSecurityGroups}
  #   # subnetIds:
  #   #   # — ${env:aws_subnet_1}
  #   #   — "subnet-7ba13b51"
  #   #   - "subnet-f4cb9e82"
    
  iamRoleStatements:
    - Effect: Allow
      Action: "ec2:*"
      Resource: "*"
    - Effect: Allow
      Action:
        - "iam:PassRole"
        - "ec2:DescribeSecurityGroups"
        - "ec2:DescribeSubnets"
        - "ec2:DescribeVpcs"
      Resource: "*"
    - Effect: Allow
      Action: "s3:*"
      Resource:
        - "Fn::Join":
            - ""
            -
              - {"Fn::GetAtt": ["ScriptBucket","Arn"]}
              - "/*"

functions:
  # Testing
  import_csv:
    handler: backend/import_csv.handler
  # Import NPI data
  npi_importer:
    handler: backend/import_npi.handler
    # vpc:
    #   securityGroupIds:
    #     # - "sg-b6039cfd"
    #     - ${env:aws_security_groups}
    #     #- ${self:custom.awsSecurityGroups}
    #   subnetIds:
    #     — ${env:aws_subnet_1}
    #     # — ${env:aws_subnet_2}

resources:
  Outputs:
    ScriptBucket:
      Value: {Ref: ScriptBucket}
  Resources:
    ScriptBucket:
      Type: "AWS::S3::Bucket"
    RDS:
      Type: AWS::RDS::DBInstance
      Properties:
        # DBName: !Ref DBName
        VPCSecurityGroups:
          - ${self:custom.awsRdsSecurityGroup}
        # - Fn::ImportValue: !Sub "${SgStackName}-RdsSG"
        AllocatedStorage: 10
        # DBInstanceClass: db.m1.medium
        DBInstanceClass: db.t2.micro
        Engine: MySQL
        MasterUsername: myusername
        MasterUserPassword: mylongpassword8888
        PubliclyAccessible: false
        # DBSubnetGroupName: !Ref SubnetGroup
        StorageType: Standard
        # DBInstanceIdentifier: !Ref DBName
      DeletionPolicy: Delete
      # DeletionPolicy: Snapshot

package:
  exclude:
    - importer/**
    - importer_env/**
    - env.python/**
    - data/**