service: importer

frameworkVersion: ">=1.9.0 <2.0.0"

plugins:
  - serverless-python-requirements
  - serverless-plugin-scripts

custom:
  stage: ${opt:stage, self:provider.stage}
  sshKey: ${env:aws_key}
  awsRegion: ${env:aws_region}
  awsImageId: ${env:aws_image_id}
  awsInstanceType: ${env:aws_instance_type}
  awsSecurityGroups: ${env:aws_security_groups}
  awsRdsSecurityGroup: ${env:aws_rds_security_group}
  # subnet1: ${env:aws_subnet_1}
  # subnet2: ${env:aws_subnet_2}
  subnet_id: ${env:aws_subnet_id}
  vpc_id: ${env:aws_vpc_id}
  db_host: {"Fn::GetAtt": ["RDS","Endpoint.Address"]}
  db_port: {"Fn::GetAtt": ["RDS","Endpoint.Port"]}
  db_user: ${env:db_user}
  db_password: ${env:db_password}
  db_schema: ${env:db_schema}
  instance_profile: ${env:instance_profile}
  pythonRequirements:
    dockerizePip: false
  scripts:
    hooks:
      'deploy:finalize': bash bin/stage_runner_to_s3.sh

provider:
  name: aws
  region: ${self:custom.awsRegion}
  runtime: python3.6
  environment:
    aws_key: ${self:custom.sshKey}
    aws_region: ${self:custom.awsRegion}
    aws_image_id: ${self:custom.awsImageId}
    aws_instance_type: ${self:custom.awsInstanceType}
    aws_security_groups: ${self:custom.awsSecurityGroups}
    aws_subnet_id: ${self:custom.subnet_id}
    aws_vpc_id: ${self:custom.vpc_id}
    # aws_subnet_1: ${self:custom.subnet1}
    # aws_subnet_2: ${self:custom.subnet2}
    s3_bucket: {Ref: ScriptBucket}
    db_host: ${self:custom.db_host}
    db_port: ${self:custom.db_port}
    db_user: ${self:custom.db_user}
    db_password: ${self:custom.db_password}
    db_schema: ${self:custom.db_schema}
    instance_profile: ${self:custom.instance_profile}
  vpc:
    securityGroupIds:
      - ${self:custom.awsSecurityGroups}
    subnetIds:
      - ${self:custom.subnet_id}
      # - ${self:custom.subnet2}
      # - "subnet-7ba13b51"
      # - "subnet-f4cb9e82"
    
  iamRoleStatements:
    - Effect: Allow
      Action: "ec2:*"
      Resource: "*"
    - Effect: Allow
      Action:
        - "iam:PassRole"
        - "ec2:DescribeSecurityGroups"
        - "ec2:DescribeSubnets"
        - "ec2:DescribeVpcs"
      Resource: "*"
    - Effect: Allow
      Action: "s3:*"
      Resource:
        - "Fn::Join":
            - ""
            -
              - {"Fn::GetAtt": ["ScriptBucket","Arn"]}
              - "/*"

functions:
  # Create the initial database
  create_db:
    handler: importer/backend/create_db.handler
  # Testing
  import_npi_ec2:
    handler: importer/backend/import_npi_ec2.handler
  # Import NPI data
  npi_importer:
    handler: importer/backend/import_npi.handler
  # Import NPI data with step function
  npi_step_importer:
    handler: importer/backend/import_npi_step.handler
    timeout: 300
    memory: 1024
  npi_stream_importer:
    handler: importer/backend/import_npi_stream.handler
  npi_unzip:
    handler: importer/backend/npi_unzip.handler
  npi_downloader:
    handler: importer/backend/npi_downloader.handler

resources:
  Outputs:
    ScriptBucket:
      Value: {Ref: ScriptBucket}
    RdsEndpoint:
      Value: {"Fn::GetAtt": ["RDS","Endpoint.Address"]}
  Resources:
    ScriptBucket:
      Type: "AWS::S3::Bucket"
    VpcEndpointEc2: ${file(resources/vpc_endpoint_ec2.yml)}
    VpcEndpointEc2Msg: ${file(resources/vpc_endpoint_ec2messages.yml)}
    VpcEndpointSsm: ${file(resources/vpc_endpoint_ssm.yml)}
    VpcEndpointS3: ${file(resources/vpc_endpoint_s3.yml)}
    NatGateway: ${file(resources/nat_gateway.yml)}
    ElasticIP: ${file(resources/elastic_ip.yml)}
    RDS:
      Type: AWS::RDS::DBInstance
      Properties:
        VPCSecurityGroups:
          - ${self:custom.awsRdsSecurityGroup}
        Engine: MySQL
        MasterUsername: ${self:custom.db_user}
        MasterUserPassword: ${self:custom.db_password}
        PubliclyAccessible: false
        #
        # Big settings
        # StorageType: gp2
        # DBInstanceClass: db.m4.large
        # AllocatedStorage: 100
        #
        # Small settings
        StorageType: Standard
        AllocatedStorage: 10
        DBInstanceClass: db.t2.micro
      DeletionPolicy: Delete

package:
  exclude:
    - env.python/**
    - env.python.old/**
    - importer.*/**
    - data/**
    - dist/**
    # - importer.*
    - "**/**/*.pyc"
    - ".env.*"