CREATE DEFINER=`{user}`@`%` PROCEDURE `{database}`.`{procedure_name}`()
BEGIN
		DROP VIEW IF EXISTS product;
        CREATE ALGORITHM=UNDEFINED DEFINER=`{user}`@`%` SQL SECURITY DEFINER VIEW `{database}`.`product` AS select distinct `{database}`.`product_master`.`Product_ID` AS `Product_ID`,`{database}`.`product_master`.`Master_Product_ID` AS `Master_Product_ID`,`{database}`.`product_master`.`Client_Product_ID` AS `Client_Product_ID`,'drug' AS `Master_Type`,`{database}`.`product_master`.`TE_Type` AS `Drug_Type`,`{database}`.`product_master`.`Source_Type` AS `Source_Type`,`{database}`.`product_master`.`ProprietaryName` AS `Name`,`{database}`.`product_master`.`ProprietaryName` AS `ProprietaryName`,`{database}`.`product_master`.`NonProprietaryName` AS `Generic_Name`,`{database}`.`product_master`.`NonProprietaryName` AS `NonProprietaryName`,'ndc' AS `Verified_source`,`{database}`.`product_master`.`Marketing_Cat_Name_Desc` AS `Verified_Source_ID`,`{database}`.`product_master`.`Eff_Date` AS `Eff_Date`,`{database}`.`product_master`.`End_Eff_Date` AS `End_Eff_Date`,`{database}`.`product_master`.`Created_By` AS `Created_By` from `{database}`.`product_master`;

		DROP VIEW IF EXISTS {database}.output_rxvantage_meddevicemaster;
		CREATE ALGORITHM=UNDEFINED DEFINER=`{user}`@`%` SQL SECURITY DEFINER VIEW `{database}`.`output_rxvantage_meddevicemaster` AS select distinct `{database}`.`device_master`.`Master_Device_ID` AS `ID`,`{database}`.`device_master`.`Device_ID` AS `DeviceID`,`{database}`.`device_master`.`DeviceID_Type` AS `DeviceIDType`,`{database}`.`device_master`.`DeviceIDIssuingAgency` AS `DeviceIdIssuingAgency`,`{database}`.`device_master`.`ContainsDINumber` AS `ContainsDINumber`,`{database}`.`device_master`.`BrandName` AS `BrandName`,`{database}`.`device_master`.`DunsNumber` AS `DunsNumber`,`{database}`.`device_master`.`PkgDiscontinueDate` AS `PkgDiscontinueDate`,`{database}`.`device_master`.`PkgStatus` AS `PkgStatus`,`{database}`.`device_master`.`Eff_Date` AS `Eff_date`,`{database}`.`device_master`.`End_Eff_Date` AS `End_Eff_Date` from `{database}`.`device_master`;

		DROP VIEW IF EXISTS {database}.output_rxvantage_meddevicemastercomplete;
		CREATE ALGORITHM=UNDEFINED DEFINER=`{user}`@`%` SQL SECURITY DEFINER VIEW `{database}`.`output_rxvantage_meddevicemastercomplete` AS select `{database}`.`device_master`.`Master_Device_ID` AS `ID`,`{database}`.`device_master`.`PrimaryDI` AS `PrimaryDI`,`{database}`.`device_master`.`Device_ID` AS `DeviceId`,`{database}`.`device_master`.`DeviceID_Type` AS `DeviceIDType`,`{database}`.`device_master`.`DeviceDescription` AS `DeviceDescription`,`{database}`.`device_master`.`CompanyName` AS `CompanyName`,`{database}`.`device_master`.`Phone` AS `Phone`,`{database}`.`device_master`.`PhoneExtension` AS `PhoneExtension`,`{database}`.`device_master`.`Email` AS `Email`,`{database}`.`device_master`.`BrandName` AS `BrandName`,`{database}`.`device_master`.`DunsNumber` AS `DunsNumber`,`{database}`.`device_master`.`DeviceIDIssuingAgency` AS `DeviceIDIssuingAgency`,`{database}`.`device_master`.`ContainsDINumber` AS `containsDINumber`,`{database}`.`device_master`.`PkgQuantity` AS `PkgQuantity`,`{database}`.`device_master`.`PkgDiscontinueDate` AS `PkgDiscontinueDate`,`{database}`.`device_master`.`PkgStatus` AS `PkgStatus`,`{database}`.`device_master`.`PkgType` AS `PkgType`,`{database}`.`device_master`.`RX` AS `RX`,`{database}`.`device_master`.`OTC` AS `OTC`,`{database}`.`device_master`.`Eff_Date` AS `Eff_Date`,`{database}`.`device_master`.`End_Eff_Date` AS `End_Eff_Date` from `{database}`.`device_master`;

		DROP VIEW IF EXISTS {database}.output_rxvantage_ndcmaster;
		CREATE ALGORITHM=UNDEFINED DEFINER=`{user}`@`%` SQL SECURITY DEFINER VIEW `{database}`.`output_rxvantage_ndcmaster` AS select distinct `{database}`.`drug_master`.`NDC_ID` AS `Master_ID`,`{database}`.`drug_master`.`LabelerName` AS `LabelerName`,`{database}`.`drug_master`.`ProductNDC` AS `ProductNDC`,`{database}`.`drug_master`.`ProprietaryName` AS `ProprietaryName`,`{database}`.`drug_master`.`NonProprietaryName` AS `NonProprietaryName`,`{database}`.`drug_master`.`ProductTypeName` AS `ProductTypeName`,`{database}`.`drug_master`.`Marketing_Cat_Name` AS `MarketingCategoryName`,`{database}`.`drug_master`.`TE_Code` AS `TE_Code`,`{database}`.`drug_master`.`TE_Type` AS `Type`,`{database}`.`drug_master`.`NDC_Exclude_Flag` AS `NDC_EXCLUDE_FLAG`,`{database}`.`drug_master`.`Ind_Drug_ID` AS `Drug_ID`,`{database}`.`drug_master`.`Ind_Drug_Name` AS `Ind_Drug_Name`,`{database}`.`drug_master`.`Ind_Name` AS `Ind_Name`,`{database}`.`drug_master`.`Ind_Status` AS `Status`,`{database}`.`drug_master`.`Ind_Phase` AS `Phase`,`{database}`.`drug_master`.`Ind_DetailedStatus` AS `Ind_DetailedStatus`,`{database}`.`drug_master`.`Eff_Date` AS `Eff_Date`,`{database}`.`drug_master`.`End_Eff_date` AS `End_Eff_Date` from `{database}`.`drug_master`;

		DROP VIEW IF EXISTS {database}.output_rxvantage_productmaster;
		CREATE ALGORITHM=UNDEFINED DEFINER=`{user}`@`%` SQL SECURITY DEFINER VIEW `{database}`.`output_rxvantage_productmaster` AS select distinct `product`.`Product_ID` AS `ID`,`product`.`Master_Product_ID` AS `Master_ID`,`product`.`Client_Product_ID` AS `Client_product_id`,`product`.`Master_Type` AS `Master_Type`,`product`.`Name` AS `Name`,`product`.`Generic_Name` AS `Generic_Name`,`product`.`Drug_Type` AS `Drug_Type`,`product`.`Source_Type` AS `Source_Type`,`product`.`Verified_source` AS `verified_source`,`product`.`Verified_Source_ID` AS `verified_source_id`,`product`.`Created_By` AS `Created_By`,`product`.`Eff_Date` AS `eff_Date`,`product`.`End_Eff_Date` AS `end_eff_date` from `{database}`.`product` where (`product`.`Master_Type` = 'drug');

		DROP VIEW IF EXISTS {database}.output_rxvantage_productmastercomplete;
		CREATE ALGORITHM=UNDEFINED DEFINER=`{user}`@`%` SQL SECURITY DEFINER VIEW `{database}`.`output_rxvantage_productmastercomplete` AS select distinct `product`.`Master_Product_ID` AS `Master_ID`,`product`.`Master_Type` AS `Master_Type`,`product`.`ProprietaryName` AS `PROPRIETARYNAME`,`product`.`NonProprietaryName` AS `NONPROPRIETARYNAME`,`product`.`Eff_Date` AS `eff_date`,`product`.`End_Eff_Date` AS `end_eff_date` from `{database}`.`product` where (`product`.`Master_Type` = 'drug');
END