CREATE DEFINER=`{user}`@`%` PROCEDURE `{database}`.`sp_create_views`()
BEGIN
		-- DROP VIEW IF EXISTS product;
        -- CREATE ALGORITHM=UNDEFINED DEFINER=`{user}`@`%` SQL SECURITY DEFINER VIEW `product` AS select distinct `product_master`.`Product_ID` AS `Product_ID`,`product_master`.`Master_Product_ID` AS `Master_Product_ID`,`product_master`.`Client_Product_ID` AS `Client_Product_ID`,'drug' AS `Master_Type`,`product_master`.`TE_Type` AS `Drug_Type`,`product_master`.`Source_Type` AS `Source_Type`,`product_master`.`ProprietaryName` AS `Name`,`product_master`.`ProprietaryName` AS `ProprietaryName`,`product_master`.`NonProprietaryName` AS `Generic_Name`,`product_master`.`NonProprietaryName` AS `NonProprietaryName`,'ndc' AS `Verified_source`,`product_master`.`Marketing_Cat_Name_Desc` AS `Verified_Source_ID`,`product_master`.`Eff_Date` AS `Eff_Date`,`product_master`.`End_Eff_Date` AS `End_Eff_Date`,`product_master`.`Created_By` AS `Created_By` from `product_master`;

		-- DROP VIEW IF EXISTS output_rxvantage_meddevicemaster;
		-- CREATE ALGORITHM=UNDEFINED DEFINER=`{user}`@`%` SQL SECURITY DEFINER VIEW `output_rxvantage_meddevicemaster` AS select distinct `device_master`.`Master_Device_ID` AS `ID`,`device_master`.`Device_ID` AS `DeviceID`,`device_master`.`DeviceID_Type` AS `DeviceIDType`,`device_master`.`DeviceIDIssuingAgency` AS `DeviceIdIssuingAgency`,`device_master`.`ContainsDINumber` AS `ContainsDINumber`,`device_master`.`BrandName` AS `BrandName`,`device_master`.`DunsNumber` AS `DunsNumber`,`device_master`.`PkgDiscontinueDate` AS `PkgDiscontinueDate`,`device_master`.`PkgStatus` AS `PkgStatus`,`device_master`.`Eff_Date` AS `Eff_date`,`device_master`.`End_Eff_Date` AS `End_Eff_Date` from `device_master`;

		-- DROP VIEW IF EXISTS output_rxvantage_meddevicemastercomplete;
		-- CREATE ALGORITHM=UNDEFINED DEFINER=`{user}`@`%` SQL SECURITY DEFINER VIEW `output_rxvantage_meddevicemastercomplete` AS select `device_master`.`Master_Device_ID` AS `ID`,`device_master`.`PrimaryDI` AS `PrimaryDI`,`device_master`.`Device_ID` AS `DeviceId`,`device_master`.`DeviceID_Type` AS `DeviceIDType`,`device_master`.`DeviceDescription` AS `DeviceDescription`,`device_master`.`CompanyName` AS `CompanyName`,`device_master`.`Phone` AS `Phone`,`device_master`.`PhoneExtension` AS `PhoneExtension`,`device_master`.`Email` AS `Email`,`device_master`.`BrandName` AS `BrandName`,`device_master`.`DunsNumber` AS `DunsNumber`,`device_master`.`DeviceIDIssuingAgency` AS `DeviceIDIssuingAgency`,`device_master`.`ContainsDINumber` AS `containsDINumber`,`device_master`.`PkgQuantity` AS `PkgQuantity`,`device_master`.`PkgDiscontinueDate` AS `PkgDiscontinueDate`,`device_master`.`PkgStatus` AS `PkgStatus`,`device_master`.`PkgType` AS `PkgType`,`device_master`.`RX` AS `RX`,`device_master`.`OTC` AS `OTC`,`device_master`.`Eff_Date` AS `Eff_Date`,`device_master`.`End_Eff_Date` AS `End_Eff_Date` from `device_master`;

		-- DROP VIEW IF EXISTS output_rxvantage_ndcmaster;
		-- CREATE ALGORITHM=UNDEFINED DEFINER=`{user}`@`%` SQL SECURITY DEFINER VIEW `output_rxvantage_ndcmaster` AS select distinct `drug_master`.`NDC_ID` AS `Master_ID`,`drug_master`.`LabelerName` AS `LabelerName`,`drug_master`.`ProductNDC` AS `ProductNDC`,`drug_master`.`ProprietaryName` AS `ProprietaryName`,`drug_master`.`NonProprietaryName` AS `NonProprietaryName`,`drug_master`.`ProductTypeName` AS `ProductTypeName`,`drug_master`.`Marketing_Cat_Name` AS `MarketingCategoryName`,`drug_master`.`TE_Code` AS `TE_Code`,`drug_master`.`TE_Type` AS `Type`,`drug_master`.`NDC_Exclude_Flag` AS `NDC_EXCLUDE_FLAG`,`drug_master`.`Ind_Drug_ID` AS `Drug_ID`,`drug_master`.`Ind_Drug_Name` AS `Ind_Drug_Name`,`drug_master`.`Ind_Name` AS `Ind_Name`,`drug_master`.`Ind_Status` AS `Status`,`drug_master`.`Ind_Phase` AS `Phase`,`drug_master`.`Ind_DetailedStatus` AS `Ind_DetailedStatus`,`drug_master`.`Eff_Date` AS `Eff_Date`,`drug_master`.`End_Eff_date` AS `End_Eff_Date` from `drug_master`;

		-- DROP VIEW IF EXISTS output_rxvantage_productmaster;
		-- CREATE ALGORITHM=UNDEFINED DEFINER=`{user}`@`%` SQL SECURITY DEFINER VIEW `output_rxvantage_productmaster` AS select distinct `product`.`Product_ID` AS `ID`,`product`.`Master_Product_ID` AS `Master_ID`,`product`.`Client_Product_ID` AS `Client_product_id`,`product`.`Master_Type` AS `Master_Type`,`product`.`Name` AS `Name`,`product`.`Generic_Name` AS `Generic_Name`,`product`.`Drug_Type` AS `Drug_Type`,`product`.`Source_Type` AS `Source_Type`,`product`.`Verified_source` AS `verified_source`,`product`.`Verified_Source_ID` AS `verified_source_id`,`product`.`Created_By` AS `Created_By`,`product`.`Eff_Date` AS `eff_Date`,`product`.`End_Eff_Date` AS `end_eff_date` from `product` where (`product`.`Master_Type` = 'drug');

		-- DROP VIEW IF EXISTS output_rxvantage_productmastercomplete;
		-- CREATE ALGORITHM=UNDEFINED DEFINER=`{user}`@`%` SQL SECURITY DEFINER VIEW `output_rxvantage_productmastercomplete` AS select distinct `product`.`Master_Product_ID` AS `Master_ID`,`product`.`Master_Type` AS `Master_Type`,`product`.`ProprietaryName` AS `PROPRIETARYNAME`,`product`.`NonProprietaryName` AS `NONPROPRIETARYNAME`,`product`.`Eff_Date` AS `eff_date`,`product`.`End_Eff_Date` AS `end_eff_date` from `product` where (`product`.`Master_Type` = 'drug');

		DROP VIEW IF EXISTS vw_DrugList;
		CREATE ALGORITHM=UNDEFINED DEFINER=`myusername`@`%` SQL SECURITY DEFINER VIEW `vw_DrugList` AS select `stage_drugVocabulary`.`Drug_ID` AS `Drug_ID`,`stage_drugVocabulary`.`Drug_Name` AS `Drug_Name` from `stage_drugVocabulary` union select distinct `stage_indications`.`Drug_ID` AS `drug_id`,`stage_indications`.`Drug_Name` AS `Drug_Name` from `stage_indications` where (not(`stage_indications`.`Drug_ID` in (select `stage_drugVocabulary`.`Drug_ID` from `stage_drugVocabulary`)));

END